quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/codex
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    migrate-at-start: true
